#!/usr/bin/env bash
# ============================================================
#  gen-secrets.sh — Interactive credential setup wizard
#
#  Run:  bash deploy/scripts/gen-secrets.sh
#
#  What it does:
#   1. Generates a secure APP_API_KEY automatically
#   2. Prompts you for each external credential (Twilio, FB)
#   3. Writes a filled-in .env file
#   4. Optionally pushes the credentials to Kubernetes
# ============================================================
set -euo pipefail

ENV_FILE=".env"
BOLD="\033[1m"
CYAN="\033[36m"
GREEN="\033[32m"
YELLOW="\033[33m"
RESET="\033[0m"

info()    { echo -e "${CYAN}→ $*${RESET}"; }
success() { echo -e "${GREEN}✓ $*${RESET}"; }
warn()    { echo -e "${YELLOW}⚠  $*${RESET}"; }
header()  { echo -e "\n${BOLD}$*${RESET}"; }

prompt_secret() {
  local var=$1 label=$2 hint=$3
  local val
  echo -e "\n  ${BOLD}${label}${RESET}"
  [ -n "$hint" ] && echo -e "  ${CYAN}${hint}${RESET}"
  read -r -p "  Value: " val
  echo "${var}=${val}" >> "$ENV_FILE"
}

prompt_plain() {
  local var=$1 label=$2 hint=$3
  local val
  echo -e "\n  ${BOLD}${label}${RESET}"
  [ -n "$hint" ] && echo -e "  ${CYAN}${hint}${RESET}"
  read -r -p "  Value: " val
  echo "${var}=${val}" >> "$ENV_FILE"
}

# -------------------------------------------------------------------
header "AI Skill Defense Console — Credential Setup Wizard"
echo   "This script builds your .env file.  Values are written locally"
echo   "and never transmitted anywhere by this script."
# -------------------------------------------------------------------

if [ -f "$ENV_FILE" ]; then
  warn ".env already exists."
  read -r -p "  Overwrite? [y/N] " confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }
fi

# Start fresh
cat > "$ENV_FILE" <<EOF
# Generated by gen-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT commit this file.

EOF

# ---- APP_API_KEY ---------------------------------------------------
header "1/3  App Security Key"
APP_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
echo "APP_API_KEY=${APP_KEY}" >> "$ENV_FILE"
success "Generated APP_API_KEY: ${APP_KEY:0:8}…${APP_KEY: -8}"

# ---- Twilio --------------------------------------------------------
header "2/3  Twilio — Real SMS + Voice Calls"
info "Sign up free at twilio.com (includes \$15 credit + a phone number)"
info "Console: https://console.twilio.com/"
echo ""

prompt_plain   TWILIO_ACCOUNT_SID   "Account SID"      "Console Dashboard → top of page, starts with AC"
prompt_secret  TWILIO_AUTH_TOKEN    "Auth Token"        "Console Dashboard → click 👁 to reveal"
prompt_plain   TWILIO_PHONE_NUMBER  "Phone Number"      "E.164 format, e.g. +15005550006"
prompt_plain   TWILIO_TWIML_APP_SID "TwiML App SID"     "Voice → TwiML Apps → Create → copy SID (starts with AP)"
prompt_plain   TWILIO_API_KEY       "API Key SID"       "Account → API Keys → Create Standard Key → copy SID (starts with SK)"
prompt_secret  TWILIO_API_SECRET    "API Key Secret"    "Shown ONCE after creation — save it now"

# ---- Facebook Messenger --------------------------------------------
header "3/3  Facebook Messenger (optional)"
info "Create app at developers.facebook.com/apps/"
info "Skip by pressing Enter — dashboard will use demo mode for Messenger"
echo ""

prompt_plain   FB_APP_ID                "App ID"               "Settings → Basic → App ID"
prompt_secret  FB_APP_SECRET            "App Secret"           "Settings → Basic → App Secret"
prompt_secret  FB_PAGE_ACCESS_TOKEN     "Page Access Token"    "Messenger → Settings → Generate Token"
prompt_plain   FB_WEBHOOK_VERIFY_TOKEN  "Webhook Verify Token" "Any string you choose (you set this in FB Webhooks)"

# ---- Public host ---------------------------------------------------
header "Production Host"
read -r -p "  Your public domain (e.g. https://console.example.com): " PUBLIC_HOST
echo "PUBLIC_HOST=${PUBLIC_HOST}" >> "$ENV_FILE"
echo "ALLOWED_ORIGINS=${PUBLIC_HOST}" >> "$ENV_FILE"

# -------------------------------------------------------------------
echo ""
success ".env written successfully."
echo ""

# ---- Optional: push to Kubernetes ----------------------------------
if command -v kubectl &>/dev/null; then
  read -r -p "Push credentials to Kubernetes now? [y/N] " do_k8s
  if [[ "$do_k8s" =~ ^[Yy]$ ]]; then
    read -r -p "Namespace [default]: " NS
    NS="${NS:-default}"
    kubectl create secret generic ai-skill-defense-secrets \
      --namespace="$NS" \
      --from-env-file="$ENV_FILE" \
      --dry-run=client -o yaml | kubectl apply -f -
    success "Kubernetes secret ai-skill-defense-secrets updated in namespace '${NS}'."
  fi
fi

echo ""
info "Next steps:"
echo "  1.  Set Twilio webhooks on your phone number:"
echo "        SMS voice: POST ${PUBLIC_HOST}/api/comms/webhook/sms"
echo "        Voice:     POST ${PUBLIC_HOST}/api/comms/webhook/voice"
echo "  2.  Deploy:  make up          (Docker Compose)"
echo "               make k8s-apply   (Kubernetes)"
echo ""
success "Done."
